linters:
  BorderZero:
    enabled: false

  Indentation:
    severity: warning
    width: 2

  StringQuotes:
    enabled: true
    style: double_quotes # or single_quotes

  ColorVariable:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false
    ignore_single_line_blocks: true

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 8

  SelectorDepth:
    enabled: true
    max_depth: 8
